# Generated by Django 2.2.6 on 2019-10-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191027_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
    ]
